services:
  # -----------------------------
  # Frontend microservices
  # -----------------------------
  ecoscolar-frontend:
    build:
      context: .
      args:
        - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
    container_name: ecoscolar-frontend
    networks:
      - frontend
    labels:
      - "wud.watch=true"
      - "wud.trigger.docker.apply=true"
      - "wud.trigger.docker.apply.mode=onnewimage"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # -----------------------------
  # Nginx API Gateway
  # -----------------------------
  ecoscolar-gateway-frontend:
    build: ecoscolar-gateway-frontend
    container_name: ecoscolar-gateway-frontend
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      ecoscolar-frontend:
        condition: service_healthy
    networks:
      - dmz
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dmz:
    driver: bridge
  frontend:
    driver: bridge
    internal : true
