worker_processes auto;

events {
    worker_connections 1024;
}

http {

    resolver 127.0.0.11:53 valid=10s;

    access_log /dev/stdout;
    error_log  /dev/stderr warn;

    server {
        listen 80;
        server_name _;

        location /health {
            access_log off;
            return 200 "OK";
        }

        proxy_connect_timeout 3s;
        proxy_read_timeout 5s;
        proxy_send_timeout 5s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_intercept_errors on;

        error_page 502 503 504 =503 /service-unavailable;

        location /service-unavailable {
            internal;
            default_type application/json;
            add_header Retry-After 30;
            return 503 '{"error":"Service temporarily unavailable"}';
        }

        location / {
            proxy_pass http://ms-frontend-proj:80;
        }
    }
}
